<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="0" tests="16" name="com.qa.voltarengel.test.VoltarengelFootTest" time="264.396" errors="2" timestamp="2023-04-23T23:50:50 IST" skipped="4">
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="cookieButton" time="7.316"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyBreadcrumbOne" time="12.721"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyBreadcrumbTwo" time="9.918"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyBreadcrumbThree" time="9.272"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyBreadcrumbFour" time="10.695"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyHyperLinkArthritisPain" time="8.416"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyHyperLinkVoltarenArthritisPainGel" time="15.365"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyShowReference" time="7.041"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyRelatedArticleReadMoreOne" time="25.355">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyRelatedArticleReadMoreOne" time="27.832">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyRelatedArticleReadMoreOne" time="26.518">
    <error message="Related Article Read More One is not preseneted in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Related Article Read More One is not preseneted in the page
at com.qa.voltarengel.pages.VoltarengelFootPage.clickRelatedArticleReadMoreOne(VoltarengelFootPage.java:231)
at com.qa.voltarengel.test.VoltarengelFootTest.verifyRelatedArticleReadMoreOne(VoltarengelFootTest.java:128)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyRelatedArticleReadMoreTwo" time="28.068">
    <error message="Related Article Read More Two is not preseneted in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Related Article Read More Two is not preseneted in the page
at com.qa.voltarengel.pages.VoltarengelFootPage.clickRelatedArticleReadMoreTwo(VoltarengelFootPage.java:244)
at com.qa.voltarengel.test.VoltarengelFootTest.verifyRelatedArticleReadMoreTwo(VoltarengelFootTest.java:140)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyRelatedArticleReadMoreTwo" time="24.257">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyRelatedArticleReadMoreTwo" time="27.640">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyGetCoupons" time="12.455"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFootTest" name="verifyBuyNow" time="11.527"/>
  <system-out/>
</testsuite> <!-- com.qa.voltarengel.test.VoltarengelFootTest -->
