<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="0" tests="6" name="com.qa.biotene.test.BioteneCancerTest" time="905.998" errors="1" timestamp="2023-04-03T07:36:54 IST" skipped="5">
  <testcase classname="com.qa.biotene.test.BioteneCancerTest" name="launchingTheUrl" time="905.998">
    <error message="Entered URL is incorrect" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Entered URL is incorrect
at com.qa.baseClass.BaseClass.launchURL(BaseClass.java:165)
at com.qa.biotene.test.BioteneCancerTest.launchingTheUrl(BioteneCancerTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- launchingTheUrl -->
  <system-out/>
  <testcase classname="com.qa.biotene.test.BioteneCancerTest" name="cookieButton" time="0.000">
    <skipped/>
  </testcase> <!-- cookieButton -->
  <system-out/>
  <testcase classname="com.qa.biotene.test.BioteneCancerTest" name="verifyLearnMore3" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLearnMore3 -->
  <system-out/>
  <testcase classname="com.qa.biotene.test.BioteneCancerTest" name="verifyLearnMore4" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLearnMore4 -->
  <system-out/>
  <testcase classname="com.qa.biotene.test.BioteneCancerTest" name="verifyLearnMore1" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLearnMore1 -->
  <system-out/>
  <testcase classname="com.qa.biotene.test.BioteneCancerTest" name="verifyLearnMore2" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLearnMore2 -->
  <system-out/>
</testsuite> <!-- com.qa.biotene.test.BioteneCancerTest -->
