<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="0" tests="21" name="com.qa.voltarengel.test.VoltarengelFamilyTest" time="307.977" errors="2" timestamp="2023-04-23T23:50:50 IST" skipped="4">
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="cookieButton" time="7.433"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyBreadcrumbOne" time="15.905"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyBreadcrumbTwo" time="14.771"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyBreadcrumbThree" time="10.349"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyBreadcrumbFour" time="13.066"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyHyperLinkPain" time="10.891"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyHyperLinkArthritisMoreManageable" time="10.537"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyHyperLinkWhatYourConditionIs" time="10.226"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyHyperLinkPainCausedByArthritis" time="9.464"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyHyperLinkStressors" time="10.115"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyHyperLinkExercise" time="11.172"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyHyperLinkVoltarenArthritisPainGel" time="14.123"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyShowReference" time="4.846"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyRelatedArticleReadMoreOne" time="24.043">
    <error message="Related Article Read More One is not preseneted in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Related Article Read More One is not preseneted in the page
at com.qa.voltarengel.pages.VoltarengelFamilyPage.clickRelatedArticleReadMoreOne(VoltarengelFamilyPage.java:311)
at com.qa.voltarengel.test.VoltarengelFamilyTest.verifyRelatedArticleReadMoreOne(VoltarengelFamilyTest.java:190)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyRelatedArticleReadMoreOne" time="25.474">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyRelatedArticleReadMoreOne" time="26.684">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyRelatedArticleReadMoreTwo" time="25.051">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyRelatedArticleReadMoreTwo" time="23.912">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyRelatedArticleReadMoreTwo" time="25.717">
    <error message="Related Article Read More Two is not preseneted in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Related Article Read More Two is not preseneted in the page
at com.qa.voltarengel.pages.VoltarengelFamilyPage.clickRelatedArticleReadMoreTwo(VoltarengelFamilyPage.java:324)
at com.qa.voltarengel.test.VoltarengelFamilyTest.verifyRelatedArticleReadMoreTwo(VoltarengelFamilyTest.java:202)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyGetCoupons" time="7.976"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelFamilyTest" name="verifyBuyNow" time="6.222"/>
  <system-out/>
</testsuite> <!-- com.qa.voltarengel.test.VoltarengelFamilyTest -->
